package com.sec421.controller.baseTools;
/**
 * @author 0x421
 * @date 2023/12/28 11:20
 * @github https://github.com/0x7eTeam
 */
import javafx.scene.control.TextArea;

import java.util.HashMap;

public class AVRecognizeController {

    public void AVCheck(TextArea textArea, String avstr){
        HashMap<String, String> avMap = new HashMap<>();
        avMap.put("360tray.exe", "360安全卫士-实时保护");
        avMap.put("360safe.exe", "360安全卫士-主程序");
        avMap.put("ZhuDongFangYu.exe", "360安全卫士-主动防御");
        avMap.put("360sd.exe", "360杀毒");
        avMap.put("a2guard.exe", "a-squared杀毒");
        avMap.put("ad-watch.exe", "Lavasoft杀毒");
        avMap.put("cleaner8.exe", "The Cleaner杀毒");
        avMap.put("vba32lder.exe", "vb32杀毒");
        avMap.put("MongoosaGUI.exe", "Mongoosa杀毒");
        avMap.put("CorantiControlCenter32.exe", "Coranti2012杀毒");
        avMap.put("F-PROT.exe", "F-Prot AntiVirus");
        avMap.put("CMCTrayIcon.exe", "CMC杀毒");
        avMap.put("K7TSecurity.exe", "K7杀毒");
        avMap.put("UnThreat.exe", "UnThreat杀毒");
        avMap.put("CKSoftShiedAntivirus4.exe", "Shield Antivirus杀毒");
        avMap.put("AVWatchService.exe", "VIRUSfighter杀毒");
        avMap.put("ArcaTasksService.exe", "ArcaVir杀毒");
        avMap.put("iptray.exe", "Immunet杀毒");
        avMap.put("PSafeSysTray.exe", "PSafe杀毒");
        avMap.put("nspupsvc.exe", "nProtect杀毒");
        avMap.put("SpywareTerminatorShield.exe", "SpywareTerminator反间谍软件");
        avMap.put("BKavService.exe", "Bkav杀毒");
        avMap.put("MsMpEng.exe", "Microsoft Security Essentials");
        avMap.put("SBAMSvc.exe", "VIPRE");
        avMap.put("ccSvcHst.exe", "Norton杀毒");
        avMap.put("f-secure.exe", "冰岛");
        avMap.put("avp.exe", "Kaspersky");
        avMap.put("KvMonXP.exe", "江民杀毒");
        avMap.put("RavMonD.exe", "瑞星杀毒");
        avMap.put("Mcshield.exe", "McAfee");
        avMap.put("Tbmon.exe", "McAfee");
        avMap.put("Frameworkservice.exe", "McAfee");
        avMap.put("egui.exe", "ESET NOD32");
        avMap.put("ekrn.exe", "ESET NOD32");
        avMap.put("eguiProxy.exe", "ESET NOD32");
        avMap.put("kxetray.exe", "金山毒霸");
        avMap.put("knsdtray.exe", "可牛杀毒");
        avMap.put("TMBMSRV.exe", "趋势杀毒");
        avMap.put("avcenter.exe", "Avira(小红伞)");
        avMap.put("avguard.exe", "Avira(小红伞)");
        avMap.put("avgnt.exe", "Avira(小红伞)");
        avMap.put("sched.exe", "Avira(小红伞)");
        avMap.put("ashDisp.exe", "Avast网络安全");
        avMap.put("rtvscan.exe", "诺顿杀毒");
        avMap.put("ccapp.exe", "SymantecNorton");
        avMap.put("NPFMntor.exe", "Norton杀毒软件");
        avMap.put("ccSetMgr.exe", "赛门铁克");
        avMap.put("ccRegVfy.exe", "Norton杀毒软件");
        avMap.put("ksafe.exe", "金山卫士");
        avMap.put("QQPCRTP.exe", "QQ电脑管家");
        avMap.put("avgwdsvc.exe", "AVG杀毒");
        avMap.put("QUHLPSVC.exe", "QUICK HEAL杀毒");
        avMap.put("mssecess.exe", "微软杀毒");
        avMap.put("SavProgress.exe", "Sophos杀毒");
        avMap.put("SophosUI.exe", "Sophos杀毒");
        avMap.put("SophosFS.exe", "Sophos杀毒");
        avMap.put("SophosHealth.exe", "Sophos杀毒");
        avMap.put("SophosSafestore64.exe", "Sophos杀毒");
        avMap.put("SophosCleanM.exe", "Sophos杀毒");
        avMap.put("fsavgui.exe", "F-Secure杀毒");
        avMap.put("vsserv.exe", "比特梵德");
        avMap.put("remupd.exe", "熊猫卫士");
        avMap.put("FortiTray.exe", "飞塔");
        avMap.put("safedog.exe", "安全狗");
        avMap.put("parmor.exe", "木马克星");
        avMap.put("Iparmor.exe.exe", "木马克星");
        avMap.put("beikesan.exe", "贝壳云安全");
        avMap.put("KSWebShield.exe", "金山网盾");
        avMap.put("TrojanHunter.exe", "木马猎手");
        avMap.put("GG.exe", "巨盾网游安全盾");
        avMap.put("adam.exe", "绿鹰安全精灵");
        avMap.put("AST.exe", "超级巡警");
        avMap.put("ananwidget.exe", "墨者安全专家");
        avMap.put("AVK.exe", "AntiVirusKit");
        avMap.put("avg.exe", "AVG Anti-Virus");
        avMap.put("spidernt.exe", "Dr.web");
        avMap.put("avgaurd.exe", "Avira Antivir");
        avMap.put("vsmon.exe", "Zone Alarm");
        avMap.put("cpf.exe", "Comodo");
        avMap.put("outpost.exe", "Outpost Firewall");
        avMap.put("rfwmain.exe", "瑞星防火墙");
        avMap.put("kpfwtray.exe", "金山网镖");
        avMap.put("FYFireWall.exe", "风云防火墙");
        avMap.put("MPMon.exe", "微点主动防御");
        avMap.put("pfw.exe", "天网防火墙");
        avMap.put("BaiduSdSvc.exe", "百度杀毒-服务进程");
        avMap.put("BaiduSdTray.exe", "百度杀毒-托盘进程");
        avMap.put("BaiduSd.exe", "百度杀毒-主程序");
        avMap.put("SafeDogGuardCenter.exe", "安全狗");
        avMap.put("safedogupdatecenter.exe", "安全狗");
        avMap.put("safedogguardcenter.exe", "安全狗");
        avMap.put("SafeDogSiteIIS.exe", "安全狗");
        avMap.put("SafeDogTray.exe", "安全狗");
        avMap.put("SafeDogServerUI.exe", "安全狗");
        avMap.put("D_Safe_Manage.exe", "D盾");
        avMap.put("d_manage.exe", "D盾");
        avMap.put("yunsuo_agent_service.exe", "云锁");
        avMap.put("yunsuo_agent_daemon.exe", "云锁");
        avMap.put("HwsPanel.exe", "护卫神");
        avMap.put("hws_ui.exe", "护卫神");
        avMap.put("hws.exe", "护卫神");
        avMap.put("hwsd.exe", "护卫神");
        avMap.put("hipsdaemon.exe", "火绒");
        avMap.put("hipstray.exe", "火绒");
        avMap.put("wsctrl.exe", "火绒");
        avMap.put("usysdiag.exe", "火绒");
        avMap.put("SPHINX.exe", "SPHINX防火墙");
        avMap.put("bddownloader.exe", "百度卫士");
        avMap.put("baiduansvx.exe", "百度卫士-主进程");
        avMap.put("AvastUI.exe", "Avast!5主程序");
        avMap.put("emet_agent.exe", "EMET");
        avMap.put("emet_service.exe", "EMET");
        avMap.put("firesvc.exe", "McAfee");
        avMap.put("firetray.exe", "McAfee");
        avMap.put("hipsvc.exe", "McAfee");
        avMap.put("mfevtps.exe", "McAfee");
        avMap.put("mcafeefire.exe", "McAfee");
        avMap.put("scan32.exe", "McAfee");
        avMap.put("shstat.exe", "McAfee");
        avMap.put("vstskmgr.exe", "McAfee");
        avMap.put("engineserver.exe", "McAfee");
        avMap.put("mfeann.exe", "McAfee");
        avMap.put("mcscript.exe", "McAfee");
        avMap.put("updaterui.exe", "McAfee");
        avMap.put("udaterui.exe", "McAfee");
        avMap.put("naprdmgr.exe", "McAfee");
        avMap.put("cleanup.exe", "McAfee");
        avMap.put("cmdagent.exe", "McAfee");
        avMap.put("frminst.exe", "McAfee");
        avMap.put("mcscript_inuse.exe", "McAfee");
        avMap.put("mctray.exe", "McAfee");
        avMap.put("_avp32.exe", "卡巴斯基");
        avMap.put("_avpcc.exe", "卡巴斯基");
        avMap.put("_avpm.exe", "卡巴斯基");
        avMap.put("aAvgApi.exe", "AVG");
        avMap.put("ackwin32.exe", "已知杀软进程,名称暂未收录");
        avMap.put("alertsvc.exe", "Norton AntiVirus");
        avMap.put("alogserv.exe", "McAfee VirusScan");
        avMap.put("anti-trojan.exe", "Anti-Trojan Elite");
        avMap.put("arr.exe", "Application Request Route");
        avMap.put("atguard.exe", "AntiVir");
        avMap.put("atupdater.exe", "已知杀软进程,名称暂未收录");
        avMap.put("atwatch.exe", "Mustek");
        avMap.put("au.exe", "NSIS");
        avMap.put("aupdate.exe", "Symantec");
        avMap.put("auto-protect.nav80try.exe", "已知杀软进程,名称暂未收录");
        avMap.put("autodown.exe", "AntiVirus AutoUpdater");
        avMap.put("avconsol.exe", "McAfee");
        avMap.put("avgcc32.exe", "AVG");
        avMap.put("avgctrl.exe", "AVG");
        avMap.put("avgemc.exe", "AVG");
        avMap.put("avgrsx.exe", "AVG");
        avMap.put("avgserv.exe", "AVG");
        avMap.put("avgserv9.exe", "AVG");
        avMap.put("avgw.exe", "AVG");
        avMap.put("avkpop.exe", "G DATA SOFTWARE AG");
        avMap.put("avkserv.exe", "G DATA SOFTWARE AG");
        avMap.put("avkservice.exe", "G DATA SOFTWARE AG");
        avMap.put("avkwctl9.exe", "G DATA SOFTWARE AG");
        avMap.put("avltmain.exe", "Panda Software Aplication");
        avMap.put("avnt.exe", "H+BEDV Datentechnik GmbH");
        avMap.put("avp32.exe", "Kaspersky Anti-Virus");
        avMap.put("avpcc.exe", " Kaspersky AntiVirus");
        avMap.put("avpdos32.exe", " Kaspersky AntiVirus");
        avMap.put("avpm.exe", " Kaspersky AntiVirus");
        avMap.put("avptc32.exe", " Kaspersky AntiVirus");
        avMap.put("avpupd.exe", " Kaspersky AntiVirus");
        avMap.put("avsynmgr.exe", "McAfee");
        avMap.put("avwin.exe", " H+BEDV");
        avMap.put("bargains.exe", "Exact Advertising SpyWare");
        avMap.put("beagle.exe", "Avast");
        avMap.put("blackd.exe", "BlackICE");
        avMap.put("blackice.exe", "BlackICE");
        avMap.put("blink.exe", "micromedia");
        avMap.put("blss.exe", "CBlaster");
        avMap.put("bootwarn.exe", "Symantec");
        avMap.put("bpc.exe", "Grokster");
        avMap.put("brasil.exe", "Exact Advertising");
        avMap.put("ccevtmgr.exe", "Norton Internet Security");
        avMap.put("cdp.exe", "CyberLink Corp.");
        avMap.put("cfd.exe", "Motive Communications");
        avMap.put("cfgwiz.exe", " Norton AntiVirus");
        avMap.put("claw95.exe", "已知杀软进程,名称暂未收录");
        avMap.put("claw95cf.exe", "已知杀软进程,名称暂未收录");
        avMap.put("clean.exe", "windows流氓软件清理大师");
        avMap.put("cleaner.exe", "windows流氓软件清理大师");
        avMap.put("cleaner3.exe", "windows流氓软件清理大师");
        avMap.put("cleanpc.exe", "windows流氓软件清理大师");
        avMap.put("cpd.exe", "McAfee");
        avMap.put("ctrl.exe", "已知杀软进程,名称暂未收录");
        avMap.put("cv.exe", "已知杀软进程,名称暂未收录");
        avMap.put("defalert.exe", "Symantec");
        avMap.put("defscangui.exe", "Symantec");
        avMap.put("defwatch.exe", "Norton Antivirus");
        avMap.put("doors.exe", "已知杀软进程,名称暂未收录");
        avMap.put("dpf.exe", "已知杀软进程,名称暂未收录");
        avMap.put("dpps2.exe", "PanicWare");
        avMap.put("dssagent.exe", "Broderbund");
        avMap.put("ecengine.exe", "已知杀软进程,名称暂未收录");
        avMap.put("emsw.exe", "Alset Inc");
        avMap.put("ent.exe", "已知杀软进程,名称暂未收录");
        avMap.put("espwatch.exe", "已知杀软进程,名称暂未收录");
        avMap.put("ethereal.exe", "RationalClearCase");
        avMap.put("exe.avxw.exe", "已知杀软进程,名称暂未收录");
        avMap.put("expert.exe", "已知杀软进程,名称暂未收录");
        avMap.put("f-prot95.exe", "已知杀软进程,名称暂未收录");
        avMap.put("fameh32.exe", "F-Secure");
        avMap.put("fast.exe", " FastUsr");
        avMap.put("fch32.exe", "F-Secure");
        avMap.put("fih32.exe", "F-Secure");
        avMap.put("findviru.exe", "F-Secure");
        avMap.put("firewall.exe", "AshampooSoftware");
        avMap.put("fnrb32.exe", "F-Secure");
        avMap.put("fp-win.exe", " F-Prot Antivirus OnDemand");
        avMap.put("fsaa.exe", "F-Secure");
        avMap.put("fsav.exe", "F-Secure");
        avMap.put("fsav32.exe", "F-Secure");
        avMap.put("fsav530stbyb.exe", "F-Secure");
        avMap.put("fsav530wtbyb.exe", "F-Secure");
        avMap.put("fsav95.exe", "F-Secure");
        avMap.put("fsgk32.exe", "F-Secure");
        avMap.put("fsm32.exe", "F-Secure");
        avMap.put("fsma32.exe", "F-Secure");
        avMap.put("fsmb32.exe", "F-Secure");
        avMap.put("gbmenu.exe", "已知杀软进程,名称暂未收录");
        avMap.put("guard.exe", "ewido");
        avMap.put("guarddog.exe", "ewido");
        avMap.put("htlog.exe", "已知杀软进程,名称暂未收录");
        avMap.put("htpatch.exe", "Silicon Integrated Systems Corporation");
        avMap.put("hwpe.exe", "已知杀软进程,名称暂未收录");
        avMap.put("iamapp.exe", "Symantec");
        avMap.put("iamserv.exe", "Symantec");
        avMap.put("iamstats.exe", "Symantec");
        avMap.put("iedriver.exe", " Urlblaze.com");
        avMap.put("iface.exe", "Panda Antivirus Module");
        avMap.put("infus.exe", "Infus Dialer");
        avMap.put("infwin.exe", "Msviewparasite");
        avMap.put("intdel.exe", "Inet Delivery");
        avMap.put("intren.exe", "已知杀软进程,名称暂未收录");
        avMap.put("jammer.exe", "已知杀软进程,名称暂未收录");
        avMap.put("kavpf.exe", "Kapersky");
        avMap.put("kazza.exe", "Kapersky");
        avMap.put("keenvalue.exe", "EUNIVERSE INC");
        avMap.put("launcher.exe", "Intercort Systems");
        avMap.put("ldpro.exe", "已知杀软进程,名称暂未收录");
        avMap.put("ldscan.exe", "Windows Trojans Inspector");
        avMap.put("localnet.exe", "已知杀软进程,名称暂未收录");
        avMap.put("luall.exe", "Symantec");
        avMap.put("luau.exe", "Symantec");
        avMap.put("lucomserver.exe", "Norton");
        avMap.put("mcagent.exe", "McAfee");
        avMap.put("mcmnhdlr.exe", "McAfee");
        avMap.put("mctool.exe", "McAfee");
        avMap.put("mcupdate.exe", "McAfee");
        avMap.put("mcvsrte.exe", "McAfee");
        avMap.put("mcvsshld.exe", "McAfee");
        avMap.put("mfin32.exe", "MyFreeInternetUpdate");
        avMap.put("mfw2en.exe", "MyFreeInternetUpdate");
        avMap.put("mfweng3.02d30.exe", "MyFreeInternetUpdate");
        avMap.put("mgavrtcl.exe", "McAfee");
        avMap.put("mgavrte.exe", "McAfee");
        avMap.put("mghtml.exe", "McAfee");
        avMap.put("mgui.exe", "BullGuard");
        avMap.put("minilog.exe", "Zone Labs Inc");
        avMap.put("mmod.exe", "EzulaInc");
        avMap.put("mostat.exe", "WurldMediaInc");
        avMap.put("mpfagent.exe", "McAfee");
        avMap.put("mpfservice.exe", "McAfee");
        avMap.put("mpftray.exe", "McAfee");
        avMap.put("mscache.exe", "Integrated Search Technologies Spyware");
        avMap.put("mscman.exe", "OdysseusMarketingInc");
        avMap.put("msmgt.exe", "Total Velocity Spyware");
        avMap.put("msvxd.exe", "W32/Datom-A");
        avMap.put("mwatch.exe", "已知杀软进程,名称暂未收录");
        avMap.put("nav.exe", "Reuters Limited");
        avMap.put("navapsvc.exe", "Norton AntiVirus");
        avMap.put("navapw32.exe", "Norton AntiVirus");
        avMap.put("navw32.exe", "Norton Antivirus");
        avMap.put("ndd32.exe", "诺顿磁盘医生");
        avMap.put("neowatchlog.exe", "已知杀软进程,名称暂未收录");
        avMap.put("netutils.exe", "已知杀软进程,名称暂未收录");
        avMap.put("nisserv.exe", "Norton");
        avMap.put("nisum.exe", "Norton");
        avMap.put("nmain.exe", "Norton");
        avMap.put("nod32.exe", "ESET Smart Security");
        avMap.put("norton_internet_secu_3.0_407.exe", "已知杀软进程,名称暂未收录");
        avMap.put("notstart.exe", "已知杀软进程,名称暂未收录");
        avMap.put("nprotect.exe", "Symantec");
        avMap.put("npscheck.exe", "Norton");
        avMap.put("npssvc.exe", "Norton");
        avMap.put("ntrtscan.exe", "趋势反病毒应用程序");
        avMap.put("nui.exe", "已知杀软进程,名称暂未收录");
        avMap.put("otfix.exe", "已知杀软进程,名称暂未收录");
        avMap.put("outpostinstall.exe", "Outpost");
        avMap.put("patch.exe", "趋势科技");
        avMap.put("pavw.exe", "已知杀软进程,名称暂未收录");
        avMap.put("pcscan.exe", "趋势科技");
        avMap.put("pdsetup.exe", "已知杀软进程,名称暂未收录");
        avMap.put("persfw.exe", "Tiny Personal Firewall");
        avMap.put("pgmonitr.exe", "PromulGate SpyWare");
        avMap.put("pingscan.exe", "已知杀软进程,名称暂未收录");
        avMap.put("platin.exe", "已知杀软进程,名称暂未收录");
        avMap.put("pop3trap.exe", "PC-cillin");
        avMap.put("poproxy.exe", "NortonAntiVirus");
        avMap.put("popscan.exe", "已知杀软进程,名称暂未收录");
        avMap.put("powerscan.exe", "Integrated Search Technologies");
        avMap.put("ppinupdt.exe", "已知杀软进程,名称暂未收录");
        avMap.put("pptbc.exe", "已知杀软进程,名称暂未收录");
        avMap.put("ppvstop.exe", "已知杀软进程,名称暂未收录");
        avMap.put("prizesurfer.exe", "Prizesurfer");
        avMap.put("prmt.exe", "OpiStat");
        avMap.put("prmvr.exe", "Adtomi");
        avMap.put("processmonitor.exe", "Sysinternals");
        avMap.put("proport.exe", "已知杀软进程,名称暂未收录");
        avMap.put("protectx.exe", "ProtectX");
        avMap.put("pspf.exe", "已知杀软进程,名称暂未收录");
        avMap.put("purge.exe", "已知杀软进程,名称暂未收录");
        avMap.put("qconsole.exe", "Norton AntiVirus Quarantine Console");
        avMap.put("qserver.exe", "Norton Internet Security");
        avMap.put("rapapp.exe", "BlackICE");
        avMap.put("rb32.exe", "RapidBlaster");
        avMap.put("rcsync.exe", "PrizeSurfer");
        avMap.put("realmon.exe", "Realmon ");
        avMap.put("rescue.exe", "已知杀软进程,名称暂未收录");
        avMap.put("rescue32.exe", "卡巴斯基互联网安全套装");
        avMap.put("rshell.exe", "已知杀软进程,名称暂未收录");
        avMap.put("rtvscn95.exe", "Real-time virus scanner ");
        avMap.put("rulaunch.exe", "McAfee User Interface");
        avMap.put("run32dll.exe", "PAL PC Spy");
        avMap.put("safeweb.exe", "PSafe Tecnologia");
        avMap.put("sbserv.exe", "Norton Antivirus");
        avMap.put("scrscan.exe", "360杀毒");
        avMap.put("sfc.exe", "System file checker");
        avMap.put("sh.exe", "MKS Toolkit for Win3");
        avMap.put("showbehind.exe", "MicroSmarts Enterprise Component ");
        avMap.put("soap.exe", "System Soap Pro");
        avMap.put("sofi.exe", "已知杀软进程,名称暂未收录");
        avMap.put("sperm.exe", "已知杀软进程,名称暂未收录");
        avMap.put("supporter5.exe", "eScorcher反病毒");
        avMap.put("symproxysvc.exe", "Symantec");
        avMap.put("symtray.exe", "Symantec");
        avMap.put("tbscan.exe", "ThunderBYTE");
        avMap.put("tc.exe", "TimeCalende");
        avMap.put("titanin.exe", "TitanHide");
        avMap.put("tvmd.exe", "Total Velocity");
        avMap.put("tvtmd.exe", " Total Velocity");
        avMap.put("vettray.exe", "eTrust");
        avMap.put("vir-help.exe", "已知杀软进程,名称暂未收录");
        avMap.put("vnpc3000.exe", "已知杀软进程,名称暂未收录");
        avMap.put("vpc32.exe", "Symantec");
        avMap.put("vpc42.exe", "Symantec");
        avMap.put("vshwin32.exe", "McAfee");
        avMap.put("vsmain.exe", "McAfee");
        avMap.put("vsstat.exe", "McAfee");
        avMap.put("wfindv32.exe", "已知杀软进程,名称暂未收录");
        avMap.put("zapro.exe", "Zone Alarm");
        avMap.put("zonealarm.exe", "Zone Alarm");
        avMap.put("AVPM.exe", "Kaspersky");
        avMap.put("A2CMD.exe", "Emsisoft Anti-Malware");
        avMap.put("A2SERVICE.exe", "a-squared free");
        avMap.put("A2FREE.exe", "a-squared Free");
        avMap.put("ADVCHK.exe", "Norton AntiVirus");
        avMap.put("AGB.exe", "安天防线");
        avMap.put("AHPROCMONSERVER.exe", "安天防线");
        avMap.put("AIRDEFENSE.exe", "AirDefense");
        avMap.put("ALERTSVC.exe", "Norton AntiVirus");
        avMap.put("AVIRA.exe", "小红伞杀毒");
        avMap.put("AMON.exe", "Tiny Personal Firewall");
        avMap.put("AVZ.exe", "AVZ");
        avMap.put("ANTIVIR.exe", "已知杀软进程,名称暂未收录");
        avMap.put("APVXDWIN.exe", "熊猫卫士");
        avMap.put("ASHMAISV.exe", "Alwil");
        avMap.put("ASHSERV.exe", "Avast Anti-virus");
        avMap.put("ASHSIMPL.exe", "AVAST!VirusCleaner");
        avMap.put("ASHWEBSV.exe", "Avast");
        avMap.put("ASWUPDSV.exe", "Avast");
        avMap.put("ASWSCAN.exe", "Avast");
        avMap.put("AVCIMAN.exe", "熊猫卫士");
        avMap.put("AVCONSOL.exe", "McAfee");
        avMap.put("AVENGINE.exe", "熊猫卫士");
        avMap.put("AVESVC.exe", "Avira AntiVir Security Service");
        avMap.put("AVEVL32.exe", "已知杀软进程,名称暂未收录");
        avMap.put("AVGAM.exe", "AVG");
        avMap.put("AVGCC.exe", "AVG");
        avMap.put("AVGCHSVX.exe", "AVG");
        avMap.put("AVGCSRVX", "AVG");
        avMap.put("AVGNSX.exe", "AVG");
        avMap.put("AVGCC32.exe", "AVG");
        avMap.put("AVGCTRL.exe", "AVG");
        avMap.put("AVGEMC.exe", "AVG");
        avMap.put("AVGFWSRV.exe", "AVG");
        avMap.put("AVGNTMGR.exe", "AVG");
        avMap.put("AVGSERV.exe", "AVG");
        avMap.put("AVGTRAY.exe", "AVG");
        avMap.put("AVGUPSVC.exe", "AVG");
        avMap.put("AVINITNT.exe", "Command AntiVirus for NT Server");
        avMap.put("AVPCC.exe", "Kaspersky");
        avMap.put("AVSERVER.exe", "Kerio MailServer");
        avMap.put("AVSCHED32.exe", "H+BEDV");
        avMap.put("AVSYNMGR.exe", "McAfee");
        avMap.put("AVWUPSRV.exe", "H+BEDV");
        avMap.put("BDSWITCH.exe", "BitDefender Module");
        avMap.put("BLACKD.exe", "BlackICE");
        avMap.put("CCEVTMGR.exe", "Symantec");
        avMap.put("CFP.exe", "COMODO");
        avMap.put("CLAMWIN.exe", "ClamWin Portable");
        avMap.put("CUREIT.exe", "DrWeb CureIT");
        avMap.put("DEFWATCH.exe", "Norton Antivirus");
        avMap.put("DRWADINS.exe", "Dr.Web");
        avMap.put("DRWEB.exe", "Dr.Web");
        avMap.put("DEFENDERDAEMON.exe", "ShadowDefender");
        avMap.put("EWIDOCTRL.exe", "Ewido Security Suite");
        avMap.put("EZANTIVIRUSREGISTRATIONCHECK.exe", "e-Trust Antivirus");
        avMap.put("FIREWALL.exe", "AshampooSoftware");
        avMap.put("FPROTTRAY.exe", "F-PROT Antivirus");
        avMap.put("FPWIN.exe", "Verizon");
        avMap.put("FRESHCLAM.exe", "ClamAV");
        avMap.put("FSAV32.exe", "F-Secure");
        avMap.put("FSBWSYS.exe", "F-secure");
        avMap.put("FSDFWD.exe", "F-Secure");
        avMap.put("FSGK32.exe", "F-Secure");
        avMap.put("FSGK32ST.exe", "F-Secure");
        avMap.put("FSMA32.exe", "F-Secure");
        avMap.put("FSMB32.exe", "F-Secure");
        avMap.put("FSSM32.exe", "F-Secure");
        avMap.put("GUARDGUI.exe", "网游保镖");
        avMap.put("GUARDNT.exe", "IKARUS");
        avMap.put("IAMAPP.exe", "Symantec");
        avMap.put("INOCIT.exe", "eTrust");
        avMap.put("INORPC.exe", "eTrust");
        avMap.put("INORT.exe", "eTrust");
        avMap.put("INOTASK.exe", "eTrust");
        avMap.put("INOUPTNG.exe", "eTrust");
        avMap.put("ISAFE.exe", "eTrust");
        avMap.put("KAV.exe", "Kaspersky");
        avMap.put("KAVMM.exe", "Kaspersky");
        avMap.put("KAVPF.exe", "Kaspersky");
        avMap.put("KAVPFW.exe", "Kaspersky");
        avMap.put("KAVSTART.exe", "Kaspersky");
        avMap.put("KAVSVC.exe", "Kaspersky");
        avMap.put("KAVSVCUI.exe", "Kaspersky");
        avMap.put("KMAILMON.exe", "金山毒霸");
        avMap.put("MCAGENT.exe", "McAfee");
        avMap.put("MCMNHDLR.exe", "McAfee");
        avMap.put("MCREGWIZ.exe", "McAfee");
        avMap.put("MCUPDATE.exe", "McAfee");
        avMap.put("MCVSSHLD.exe", "McAfee");
        avMap.put("MINILOG.exe", "Zone Alarm");
        avMap.put("MYAGTSVC.exe", "McAfee");
        avMap.put("MYAGTTRY.exe", "McAfee");
        avMap.put("NAVAPSVC.exe", "Norton");
        avMap.put("NAVAPW32.exe", "Norton");
        avMap.put("NAVLU32.exe", "Norton");
        avMap.put("NAVW32.exe", "Norton Antivirus");
        avMap.put("NEOWATCHLOG.exe", "NeoWatch");
        avMap.put("NEOWATCHTRAY.exe", "NeoWatch");
        avMap.put("NISSERV.exe", "Norton");
        avMap.put("NISUM.exe", "Norton");
        avMap.put("NMAIN.exe", "Norton");
        avMap.put("NOD32.exe", "ESET NOD32");
        avMap.put("NPFMSG.exe", "Norman个人防火墙");
        avMap.put("NPROTECT.exe", "Symantec");
        avMap.put("NSMDTR.exe", "Norton");
        avMap.put("NTRTSCAN.exe", "趋势科技");
        avMap.put("OFCPFWSVC.exe", "OfficeScanNT");
        avMap.put("ONLINENT.exe", "已知杀软进程,名称暂未收录");
        avMap.put("OP_MON.exe", " OutpostFirewall");
        avMap.put("PAVFIRES.exe", "熊猫卫士");
        avMap.put("PAVFNSVR.exe", "熊猫卫士");
        avMap.put("PAVKRE.exe", "熊猫卫士");
        avMap.put("PAVPROT.exe", "熊猫卫士");
        avMap.put("PAVPROXY.exe", "熊猫卫士");
        avMap.put("PAVPRSRV.exe", "熊猫卫士");
        avMap.put("PAVSRV51.exe", "熊猫卫士");
        avMap.put("PAVSS.exe", "熊猫卫士");
        avMap.put("PCCGUIDE.exe", "PC-cillin");
        avMap.put("PCCIOMON.exe", "PC-cillin");
        avMap.put("PCCNTMON.exe", "PC-cillin");
        avMap.put("PCCPFW.exe", "趋势科技");
        avMap.put("PCCTLCOM.exe", "趋势科技");
        avMap.put("PCTAV.exe", "PC Tools AntiVirus");
        avMap.put("PERSFW.exe", "Tiny Personal Firewall");
        avMap.put("PERVAC.exe", "已知杀软进程,名称暂未收录");
        avMap.put("PESTPATROL.exe", "Ikarus");
        avMap.put("PREVSRV.exe", "熊猫卫士");
        avMap.put("RTVSCN95.exe", "Real-time Virus Scanner");
        avMap.put("SAVADMINSERVICE.exe", "SAV");
        avMap.put("SAVMAIN.exe", "SAV");
        avMap.put("SAVSCAN.exe", "SAV");
        avMap.put("SDHELP.exe", "Spyware Doctor");
        avMap.put("SHSTAT.exe", "McAfee");
        avMap.put("SPBBCSVC.exe", "Symantec");
        avMap.put("SPIDERCPL.exe", "Dr.Web");
        avMap.put("SPIDERML.exe", "Dr.Web");
        avMap.put("SPIDERUI.exe", "Dr.Web");
        avMap.put("SPYBOTSD.exe", "Spybot ");
        avMap.put("SWAGENT.exe", "SonicWALL");
        avMap.put("SWDOCTOR.exe", "SonicWALL");
        avMap.put("SWNETSUP.exe", "Sophos");
        avMap.put("SYMLCSVC.exe", "Symantec");
        avMap.put("SYMPROXYSVC.exe", "Symantec");
        avMap.put("SYMSPORT.exe", "Sysmantec");
        avMap.put("SYMWSC.exe", "Sysmantec");
        avMap.put("SYNMGR.exe", "Sysmantec");
        avMap.put("TMLISTEN.exe", "趋势科技");
        avMap.put("TMNTSRV.exe", "趋势科技");
        avMap.put("TMPROXY.exe", "趋势科技");
        avMap.put("TNBUTIL.exe", "Anti-Virus");
        avMap.put("VBA32ECM.exe", "已知杀软进程,名称暂未收录");
        avMap.put("VBA32IFS.exe", "已知杀软进程,名称暂未收录");
        avMap.put("VBA32PP3.exe", "已知杀软进程,名称暂未收录");
        avMap.put("VCRMON.exe", "VirusChaser");
        avMap.put("VRMONNT.exe", "HAURI");
        avMap.put("VRMONSVC.exe", "HAURI");
        avMap.put("VSHWIN32.exe", "McAfee");
        avMap.put("VSSTAT.exe", "McAfee");
        avMap.put("XCOMMSVR.exe", "BitDefender");
        avMap.put("ZONEALARM.exe", "Zone Alarm");
        avMap.put("360rp.exe", "360杀毒");
        avMap.put("afwServ.exe", " Avast Antivirus");
        avMap.put("safeboxTray.exe", "360杀毒");
        avMap.put("360safebox.exe", "360杀毒");
        avMap.put("QQPCTray.exe", "QQ电脑管家");
        avMap.put("KSafeTray.exe", "金山毒霸");
        avMap.put("KSafeSvc.exe", "金山毒霸");
        avMap.put("KWatch.exe", "金山毒霸");
        avMap.put("gov_defence_service.exe", "云锁");
        avMap.put("gov_defence_daemon.exe", "云锁");
        avMap.put("smartscreen.exe", "Windows Defender");
        avMap.put("securityhealthservice.exe", "Windows Defender");
        avMap.put("SunloginClient.exe", "向日葵");
        avMap.put("finalshell.exe", "finalshell终端管理");
        avMap.put("navicat.exe", "数据库管理");
        avMap.put("AliSecGuard.exe", "阿里云盾");
        avMap.put("AliYunDunUpdate.exe", "阿里云盾");
        avMap.put("AliYunDun.exe", "阿里云盾");
        avMap.put("CmsGoAgent.windows-amd64.", "阿里云监控");
        avMap.put("vmnetdhcp.exe", "vm虚拟机");
        avMap.put("ToDesk.exe", "ToDesk远控");
        avMap.put("ToDesk_Service.exe", "ToDesk远控");

        String av_result="";
        for (String key : avMap.keySet()) {
            if (avstr.contains(key)) {
                String value = avMap.get(key);
                av_result += "进程: " + key + ", 疑似: " + value +"\t\r\n";
            }
        }

        textArea.setText(av_result);
    }

}
